### ISSUE TITLE
Merchant Authentication - Where? How?

### ISSUE THREAD

**Issue by cyberphone** [digitallabor-berlin/eudiw-sca#2]
It is not clear to me where and how the authenticity of the Merchant is performed.

Existing payment systems use intermediaries like Stripe, and Adyen for this purpose.  Using Open banking this would presumably be the PISP although this is not specified by for example the Berlin group.

**Comment by senexi** [comment]
Please check chapter 5 of the Berlin Groups Implementation Guidelines. The flow presented here does not deviate from the flows that are already used today.

https://www.berlin-group.org/_files/ugd/c2914b_fec1852ec9c640568f5c0b420acf67d2.pdf
