### ISSUE TITLE
Privacy Considerations

### ISSUE THREAD

**Issue by cyberphone** [digitallabor-berlin/eudiw-sca#3]
From what I can deduct the Merchant gets the unencrypted credential data in the Open Banking model.
To me this is neither ideal nor necessary; the Merchant only needs a receipt that it has been (or is about to be) paid.

In my take on the matter the Issuer is the only party who can read (after decryption) and verify a payment authorization.

**Comment by senexi** [comment]
The payment credential only contains the information about the payment mean. You can hardly do a payment without letting the merchant know how you actually want to pay....
